### ISSUE TITLE
OpenCPN plugin fails to connect to pypilot if config dialog window not visited

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#221]
OpenCPN plugin fails to connect to pypilot if config dialog window not visited.

I have to open/close config dialog of pypilot plugin on each OpenCPN restart

**Comment by seandepagnier** [comment]
try   pulling from git master I fixed a stupid bug just now

**Comment by mgrouch** [comment]
Would it be in https://github.com/pypilot/pypilot_pi  ?

I do not see any changes

**Comment by marcobergman** [comment]
Where was this change made? Don't see it either. Thx.

**Comment by mgrouch** [comment]
> Where was this change made? Don't see it either. Thx.

There was no change to fix it. It’s still not fixed. 
I’ve reported it in OpenCPN  plugin github projects.

**Comment by Steve111888** [comment]
"There are GPIO conflicts between the following apps: GPIO - 1W, pypilot - pypilot hat" ???
